version: "3"

services:
  web:
    restart: always
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "${PORT:-80}:80"
